sudo: required
dist: trusty
language: node_js
node_js: '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: tech@bessemeralliance.com
  api_key:
    secure: czoyL8+gWs+tuygFnxxVQHv3ocN0aSCxCOfUcJAWHfYaFRbS7g38zCPiivBCKih6CSGm/YPXElUPomUsZLatMbPaahk4q2j9JDLl4KKdUz/1wA4JYl6Z4M8kstl+Dx5klEash+NmTVP+xx4u7aiKDz3Jtf91vjb5hVG4fuxWiV7mkB6gPHdzobT7XangMkWNao9nhmJNkoJehVhaLuMMLH6zTDk36IQ2VZBY/w8gCKOpGLRoA9Gcl/9yDT2emXSK9CkRIo9FEtGsx15dal5yYZ4IsNVGPfZ7w2/tmNedbBgnb8EUmNje1IzxHhfxakvX6LTd1MAJ2/VrgYz8CRo4BA4mnDZrkQRjle6yBUYhIN5zc552Ca7fPyPNqZH8/xHMXtc/f6pBZ2zzvFqeMBdF70BZmtWE26Q19eohEP3Eof8DcMmzzRXE+OzGuSDIWJUw4m/IWgleUXAeSS/D+E4FkeFH38NO6+SDEPwQwGYyRx0LLPjK446AgkB+0enJS+bWtKooZ8290nGkm7wjmiz32UBbcim32PNLXDwGiQVc4n++Js3Ky+d7X4w0xGexpwiGHUbWDIZoDmEA9wK8Tbec+dFUX79aJuShaALIxCyZQwB3bc1qRDtT1I80v1ORETfaxGkdVFvCSWEJW7g2A7y/qk/AidQg+riWLHzP1DAOBBQ=
  on:
    tags: true
