sudo: required
dist: trusty
language: node_js
node_js: '6'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: tech@bessemeralliance.com
  api_key:
    secure: ZupWj24D1NQD07l6BDQSJYj3+XVJLLVVg4hp9Guqr6Qam1vUUW3Yul4d0H3MRiGAR/i6mgkw+4bo/dgs6rOhRk4DyMdyWDXFejc/D4+Ow/i2m/QKjx3RTyNc2oqG/4f4VkfL1t1KQyfppuHn9vuhaHFz0oG+lna67gGHf3S3FMhu/9/uhtJ2AxphN2huW8nDX5J3CTBMYyRobEikyghAFGkHf5MIvLipQx/wIGFnwitBskjSVSBq3TmVl8Y4pdkUnCI1/miWHdfvywcyjwYg0X6I6W/zPicRFeiKSOH9bjyRzcJc2+ssE94ZWKOfKaTAK6voNXbIh2pgqZb8uheWk61f+wpo3lFySf6mA3SedpnPr7gwVoeSVrWRy8sByhjESoNwvZa/qLnjx4QZb3Aqrq5F6ercSCcxCSXm+1eQLZoRln1p67n5LYGWbRt7s1TlqZuRKWVFlxBMbapVsnjmNTpCwyVZuMLJpZFHBirM0y17ITjSIXv1nW93lcnUNKx7moNJubPC2nzKCdSrxy8A7AuZA876XHPsKW/i+iouIZSMgGyEaBUbIP5EnCiDVdg0ajdafuY/iPRhxvkcBZ82yYF6jjBpIY6e3RPRimvb06uiioRHMZjxJtXrt1g5FLdX7CDTCj4RWHgSLD3Ziwpp3Odh3yHGpPjfmvs3sDxLWfQ=
  on:
    tags: true
